# Generated by Django 5.0.6 on 2025-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('claim_type', models.CharField(choices=[('HEALTH', 'Health'), ('VEHICLE', 'Vehicle'), ('PROPERTY', 'Property'), ('LIFE', 'Life'), ('TRAVEL', 'Travel')], max_length=20)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='claims/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('DISCHARGED', 'Discharged')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
